# Generated by Django 4.2.1 on 2023-06-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToysApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ages',
            name='age',
            field=models.CharField(max_length=30),
        ),
    ]
