# Generated by Django 4.2.1 on 2023-06-04 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToysApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toys',
            name='box_size',
        ),
        migrations.AddField(
            model_name='toys',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='age_toys', to='ToysApp.ages'),
        ),
        migrations.AddField(
            model_name='toys',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_toys', to='ToysApp.category'),
        ),
        migrations.AddField(
            model_name='toys',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender_toys', to='ToysApp.gendertype'),
        ),
        migrations.AddField(
            model_name='toys',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
