# Generated by Django 4.2.1 on 2023-06-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToysApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendertype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
