# Generated by Django 4.2.1 on 2023-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToysApp', '0002_remove_toys_box_size_toys_age_toys_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toys',
            name='video_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
