# Generated by Django 4.2.1 on 2023-06-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToysApp', '0002_alter_ages_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='toys',
            name='vl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
