# Generated by Django 4.2.1 on 2023-06-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToysApp', '0003_toys_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toys',
            old_name='finished',
            new_name='available',
        ),
        migrations.AlterField(
            model_name='toys',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
