# Generated by Django 4.2.1 on 2023-06-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToysApp', '0003_toys_vl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toys',
            name='vl',
        ),
        migrations.AlterField(
            model_name='toys',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
