# Generated by Django 4.2.1 on 2023-06-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToysApp', '0004_rename_finished_toys_available_alter_toys_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='toys',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='toys',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='Toys/media'),
        ),
    ]
