# Generated by Django 4.2.1 on 2023-07-02 12:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('ToysApp', '0004_remove_toys_vl_alter_toys_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toys',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
