# Generated by Django 4.2.1 on 2023-06-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('is-light', 'Light'), ('is-success', 'Green'), ('is-warning', 'Yellow'), ('is-info', 'Blue'), ('is-dark', 'Dark')], default='is-success', max_length=50),
        ),
    ]
