# Generated by Django 4.2.1 on 2023-06-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rporterGeoSpatial', '0004_irn_adm1_delete_tmworldborders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irn_adm1',
            name='varname_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
