# Generated by Django 4.2.1 on 2023-06-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rporterGeoSpatial', '0005_alter_irn_adm1_varname_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irn_adm1',
            name='nl_name_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
