# Generated by Django 4.2.1 on 2023-06-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rporterGeoSpatial', '0006_alter_irn_adm1_nl_name_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='incidences',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidences',
            name='geo_tag_photo',
            field=models.ImageField(blank=True, null=True, upload_to='geoTag_Image'),
        ),
        migrations.AddField(
            model_name='incidences',
            name='variety',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidences',
            name='health_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_status', to='rporterGeoSpatial.healthstatus'),
        ),
    ]
