# Generated by Django 4.2.1 on 2023-06-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rporterGeoSpatial', '0007_healthstatus_incidences_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidences',
            name='disease_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidences',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
